- name: Create the Development Environment
  hosts: localhost
  become: true
  tasks:
    - name: Set KUBECONFIG environment variable
      lineinfile:
        path: /etc/environment
        line: "KUBECONFIG=/tmp/k3s.yaml"
        create: true

    - name: Create Development Namespace
      kubernetes.core.k8s:
        name: development
        api_version: v1
        kind: Namespace
        state: present

    - name: Apply mendhak/http-https-echo Manifests
      kubernetes.core.k8s:
        state: present
        src: "{{ item }}"
      loop:
        - k8s-manifests/http-https-echo-deployment.yml
        - k8s-manifests/http-https-echo-service.yml

    - name: Add the Bitnami Helm repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Install Bitnami PostgreSQL Operator using Helm
      kubernetes.core.helm:
        name: postgresql-ha
        chart_ref: bitnami/postgresql-ha
        release_namespace: "development"
        update_repo_cache: true
        state: present

    - name: Apply postgresql-ha Manifests
      kubernetes.core.k8s:
        state: present
        src: k8s-manifests/postgresql-nodeport-service.yml