- name: Download and install K3s (Master)
  shell: |
    curl -sfL {{ k3s_install_url }} | INSTALL_K3S_VERSION={{ k3s_version }} sh -
  args:
    creates: /usr/local/bin/k3s

- name: Get K3s token for agent registration
  command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  changed_when: false

- name: Set K3s token fact
  set_fact:
    k3s_token: "{{ k3s_token.stdout }}"

- name: Ensure K3s is running (Master)
  systemd:
    name: k3s
    state: started
    enabled: true
