apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
  namespace: development
spec:
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: https
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: http-echo-nodeport-service
  namespace: development
spec:
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31080 
      name: http
    - protocol: TCP
      port: 8443
      targetPort: 8443
      nodePort: 31443
      name: https
  type: NodePort


