apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: development
  labels:
    app: http-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
        - name: http-echo
          image: mendhak/http-https-echo:latest
          ports:
            - containerPort: 8080
            - containerPort: 8443
