apiVersion: v1
kind: Service
metadata:
  name: postgresql-nodeport-service
  namespace: development
spec:
  selector:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: postgresql-ha
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432  
      nodePort: 30432 
      name: postgres
  type: NodePort


